### ISSUE TITLE
Record real responses without mocking requests

### ISSUE THREAD

**Issue by Gummibeer** [Sammyjo20/saloon-laravel#14]
With Laravel HTTP client you can record responses from real requests. This is useful to generate an initial fixture set for your tests and don't have to create them manually. In the best case Saloon would work the same - so it would switch to a partial mocking approach and record every mocked and real response. Possibly with an `isMocked = true` flag but not important. That way you could list unmocked requests somewhere and automatically create fixtures to make them mocked in the next run or whatever you want but don't break/fail the execution.

In Laravel it's part of the partial HTTP client mocking approach. As soon as you call `Http::fake()` it will record every request/response.
* `\Illuminate\Http\Client\Factory::record`
* `\Illuminate\Http\Client\Factory::recorded`

Below an example from [TMDB](https://github.com/Astrotomic/laravel-tmdb) test code:
```php
protected function tearDown(): void
{
    foreach (Http::recorded() as $record) {
        /**
         * @var \Illuminate\Http\Client\Request $request
         * @var \Illuminate\Http\Client\Response $response
         */
        [$request, $response] = $record;

        if ($response->successful()) {
            $filepath = $this->fixturePath(
                Str::after(parse_url($request->url(), PHP_URL_PATH), '/3/'),
                parse_url($request->url(), PHP_URL_QUERY)
            );

            File::ensureDirectoryExists(dirname($filepath));
            File::put(
                $filepath,
                json_encode($response->json(), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)
            );
        }
    }

    parent::tearDown();
}
```

**Comment by Sammyjo20** [comment]
Thanks for the detail @Gummibeer!

I have introduced this in #16 🥳
