### ISSUE TITLE
Group requests on connector

### ISSUE THREAD

**Issue by Gummibeer** [Sammyjo20/saloon-laravel#15]
It would be cool to group requests by any meaning - for example the primary entity. That way the method names would be shorter.
A real problem I see with that is the missing autocompletion. Right now you can at least add `@method AllMoviesRequest allMoviesRequest()` doc-block. That's not possible anymore as I only can annotate the `->movies` property but not the methods available on it. 

```php
$requests = [
    'movies' => [
        'all' => AllMoviesRequest::class,
    ],
];

$sdk->movies->all()->send()->json();
```

I assume that it would be added to the core with a new class `Proxy` (tbd) which retrieves an instance of the connector and the array of method to requests mappings. Benefit: this could be easily enhanced to a multi-level thing like GitHub API for example `$github->user->repo->show($username, $reponame)` As it would just pen another instance of that proxy.

**Comment by Sammyjo20** [comment]
I have introduced this as PR in the core Sammyjo20/Saloon package as this can be shared across Laravel and Non-Laravel projects.

See the PR here: I have introduced this into Saloon's core in a PR here:
