### ISSUE TITLE
`\Sammyjo20\Saloon\Http\SaloonRequest::getFullRequestUrl()` does not contain query params

### ISSUE THREAD

**Issue by Gummibeer** [Sammyjo20/saloon-laravel#17]
I assumed that the `\Sammyjo20\Saloon\Http\SaloonRequest::getFullRequestUrl` method returns, well, the **full** request URL. Fr me this includes the query params as well.

How can I retrieve the **full** URL used for the request from the response? 🤔
Using `$request->getQuery()` doesn't 100% feel right/reliable as theoretically the return value could change between running the request and asking for the used query string.

**Comment by Sammyjo20** [comment]
Hey @Gummibeer 

Unfortunately, there is no way to get the final query parameters, except the "getQuery". You could grab them from within a request handler but I know that's messy.

What's the use case?

**Comment by Gummibeer** [comment]
My response mock fixture file generator. As the query params are important for TMDB API as they control the response content.

But also useful for exceptions, logging and stuff like that to log the real full URL.

**Comment by Sammyjo20** [comment]
This although is a little misleading is currently going to remain unchanged. I have changed the name of the method in the v2 branch, as well as the PendingSaloonRequest that you will get in your fixtures will have all of the request properties like query parameters which you can trust.
