### ISSUE TITLE
Commands for Responses

### ISSUE THREAD

**Issue by Wulfheart** [Sammyjo20/saloon-laravel#2]
Related to https://github.com/Sammyjo20/Saloon/issues/11. 

I think we should add a command `php artisan saloon:response` and also a flag to `pa saloon:request SomeRequest -r SomeResponse` which already prefills the request. 

What do you think about it?

**Comment by Wulfheart** [comment]
Update: It seems that the response command is more or less updated. I still propose another flag to create a matching response on the fly.

**Comment by Sammyjo20** [comment]
Did you want to PR this as well as what we discussed in #4 ? I imagine it would just be `php artisan make:request --integration --response` and if you don't specify a response, it will put it in the root "Integrations/Responses" folder

**Comment by Sammyjo20** [comment]
I think I'm going to close this for now, since there is a command to create a response I think in the future we could introduce a flag to the request command that allows you to specify the connector.
