### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by Wulfheart** [Sammyjo20/saloon-laravel#4]
Currently the cli commands generate requests, responses and connectors in separate folders.
However, when writing multiple API integrations it becomes messy when these three from different applications become mixed up. Therefore I propose an refined command line experience consisting of the following:
1. I like the location in the Http folder as it deals with outgoing Http requests. I don't like the name Saloon for that folder. I suppose it is for branding purposes but I don't think that it is the right way forward because it doesn't clearly convey the purpose of the directory. I think it should be named something like `Integration`.
2. Furthermore I fear that different integrations become mixed up in a context with multiple integrations. Therefore I think it should contain multiple directories with the current structure in them (but the `Connectors` directory omitted as there is only one connector per API I suppose).
```
app/
├─ Http/
│  ├─ Integration/
│  │  ├─ Integration1/
│  │  │  ├─ Requests/
│  │  │  ├─ Responses/
│  │  │  ├─ Integration1Connector.php
│  │  ├─ Integration2/
│  │  │  ├─ Requests/
│  │  │  ├─ Responses/
│  │  │  ├─ Integration2Connector.php
```

3. Number 2 would also lead to an additional flag called something like `-i|--integration` to specify which integration is intended to have an addition.

What do you think about it?

I'd be willing to contribute this addition.

**Comment by Sammyjo20** [comment]
I like this new folder structure. The old one was sort of thrown together but I found this too, it would be really nice if each integration had a dedicated folder with its own requests inside of a folder too. 

I don't really know too much about "Make" commands, but I like the idea of specifying `php artisan make:request --integration|--i`. 

If I didn't specify `--integration`, what would the default behaviour be? Like this?

```
app/
├─ Http/
│  ├─ Requests/
│  ├─ Responses/
│  ├─ Integration1Connector.php
```

**Comment by Wulfheart** [comment]
> I don't really know too much about "Make" commands, but I like the idea of specifying php artisan make:request --integration|--i. I guess it will just prefix the namespace?

Correct. But in addition to that it will always be put in the `app/Http/Integration` folder. The -i is, in contrary to what I stated earlier, not a flag. It will be used like `pa saloon:request -i Forge` which then will create an integration even if it doesn't exist. I am going to create a draft where you can see what it is about.
