### ISSUE TITLE
Dispatching HTTP client events so network requests can be inspected in Telescope

### ISSUE THREAD

**Issue by mabdullahsari** [Sammyjo20/saloon-laravel#43]
Hi 👋

I tried inspecting outgoing network requests using Telescope, but it seems like Saloon's Laravel adapter doesn't dispatch the Laravel HTTP Client events. 

Telescope's "HTTP Client" tab relies on these events:

- `Illuminate\Http\Client\Events\ConnectionFailed`
- `Illuminate\Http\Client\Events\RequestSending`
- `Illuminate\Http\Client\Events\ResponseReceived`

I was going to send in a PR, but it seems like Saloon does not make use of `Psr\Http\Message\{RequestInterface, ResponseInterface}` so I could not instantiate an `Illuminate\Http\Client\{Request, Response}` which all of the events need.

This would be a huge QoL improvement, so what would you suggest in this case? 
I'm definitely open to submitting PRs, but first would like to know how you would like to proceed.

Thank you 🙌

**Comment by Sammyjo20** [comment]
Hey @mabdullahsari are you using the Laravel HTTP Sender for Saloon? 

https://github.com/Sammyjo20/saloon-http-sender

https://docs.saloon.dev/digging-deeper/laravel-integration

**Comment by mabdullahsari** [comment]
> Hey @mabdullahsari are you using the Laravel HTTP Sender for Saloon?
> 
> https://github.com/Sammyjo20/saloon-http-sender
> 
> https://docs.saloon.dev/digging-deeper/laravel-integration#laravel-http-client-sender

I was not... 🫠 I'm so sorry for wastig your time. 

Have a great day further!
