### ISSUE TITLE
Error updating version 2.0.0-beta6 to 2.0.1

### ISSUE THREAD

**Issue by RiverMartinezG** [Sammyjo20/saloon-laravel#44]
Hello,
I am trying to upgrade a Laravel project with the sammyjo20/saloon-laravel package from version 2.0.0-beta6 to version 2.0.1 but I get the following error:

```
Call to undefined method Saloon\Helpers\Config::resolveSenderWith()

at vendor/sammyjo20/saloon-laravel/src/SaloonServiceProvider.php:55
```

![image](https://github.com/Sammyjo20/Saloon/assets/1312549/69103ebc-abba-45ff-83f6-36dd4671a6c5)

How can I fix this error?

Laravel Version: 9.39.0
PHP version: 8.1.10

**Comment by Sammyjo20** [comment]
Hey @RiverMartinezG 

Hmm this is strange. Have you tried removing the library first, so Laravel unregisters it from their service providers and then requiring it again?

`composer remove sammyjo20/saloon-laravel && composer require sammyjo20/saloon-laravel "^2.0"`

**Comment by RiverMartinezG** [comment]
Hi @Sammyjo20 
Thanks for the reply, I solved the problem by removing the package-lock.json and re-running:

`composer require sammyjo20/saloon-laravel "^2.0"`
